#ifndef SETTINGS_H
#define SETTINGS_H

enum OPTIONS_ID {
    CADASTRAR_PERFIL = 1,
    BUSCAR_PERFIL_EMAIL,
    LISTAR_PERFIL_ANO,
    LISTAR_PERFIL_HABILIDADE,
    LISTAR_PERFIL_CURSO,
    LISTAR_PERFIS_COMPLETO,
    DELETAR_PERFIL,
    SAIR
};

#endif